SELECT ADD_MONTHS(SYSDATE, 6) "6개월후", ADD_MONTHS(SYSDATE, -6) "6개월전" FROM DUAL;

SELECT LAST_DAY(SYSDATE) FROM DUAL;

/*
SELECT 
	SYSDATE -1 yesterday,
	SYSDATE today,
	SYSDATE +1 tomorrow
FROM dual; -- docker 기준

SELECT * FROM EMP e;
SELECT EMPNO, ENAME, HIREDATE, SYSDATE - HIREDATE 경과일수, 
MONTHS_BETWEEN(HIREDATE, SYSDATE) "경과 개월수", FROM EMP e ;
*/


--SELECT SYSDATE FROM dual;

/*SELECT  * FROM EMP e WHERE SAL < 2900
UNION ALL
SELECT * FROM EMP e WHERE SAL >2000;*/


--SELECT * FROM EMP e WHERE SAL < 2900 ORDER BY SAL;

--SELECT EMPNO, ENAME, SAL, SAL * 12 + NVL(COMM, 0) 연봉 FROM EMP e ;
--SELECT * FROM EMP e WHERE COMM IS NULL;
--SELECT * FROM EMP e WHERE COMM IS NOT NULL;

--SELECT NULL + 100 FROM DUAL;

--SELECT * FROM EMP e WHERE ENAME LIKE 'S%' AND ENAME LIKE '%H';
--SELECT * FROM EMP e WHERE ENAME LIKE '%A%';
--SELECT * FROM EMP e WHERE ENAME LIKE '_A%';

--SELECT * FROM EMP e WHERE JOB LIKE 'SALESMAN';

--SELECT * FROM EMP e
--WHERE HIREDATE BETWEEN TO_DATE('1981-01-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') AND
--TO_DATE('1981-12-31 23:59:59', 'yyyy-mm-dd hh24:mi:ss');


--SELECT * FROM EMP e
--WHERE HIREDATE >= TO_DATE('1981-01-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') AND
--HIREDATE <= TO_DATE('1981-12-31 23:59:59', 'yyyy-mm-dd hh24:mi:ss');

--SELECT * FROM EMP e WHERE JOB ='SALESMAN' OR JOB = 'MANAGER' OR JOB = 'CLERK';
--
--SELECT * FROM EMP e WHERE JOB IN ('SALESMAN', 'MANAGER', 'CLERK');


--SELECT * FROM EMP WHERE SAL >= 1500 AND SAL < 3000 ORDER BY SAL;
--
--SELECT * FROM EMP WHERE NOT(SAL >= 1500 AND SAL < 3000) ORDER BY SAL;
--
--
--SELECT * FROM EMP WHERE JOB = 'SALESMAN' OR (JOB ='MANAGER' AND SAL > 2500);
--
--SELECT * FROM EMP WHERE NOT (JOB = 'SALESMAN' OR (JOB ='MANAGER' AND SAL > 2500));


--SELECT DISTINCT DEPTNO, JOB FROM EMP;
--
--SELECT EMPNO, ENAME, SAL, SAL * 12 "YEARSAL" FROM EMP e;
--
--SELECT 10 * 10 FROM DUAL;
--
--SELECT EMPNO, ENAME, SAL FROM EMP ORDER BY SAL ASC;
--
--SELECT EMPNO, ENAME, SAL FROM EMP ORDER BY SAL DESC, EMPNO  DESC;